// GENERATED by scripts/pin-deno-sidecar.ts -- run it after bumping .dvmrc.
//
// sha256 of each pinned deno release archive. downloadSidecar REFUSES a target with no
// entry here rather than installing an unverifiable binary, so this table is the thing
// that makes sidecar provisioning safe.
import type { DenoReleaseTarget } from "./sidecar.ts";

export const DENO_SIDECAR_PINS: Readonly<
  Record<string, Readonly<Partial<Record<DenoReleaseTarget, string>>>>
> = {
  "2.9.5": {
    "aarch64-apple-darwin": "b796aadd131f6930560c1ee040cf0d6f53933fbb987464e9ff46bd7ea4830615",
    "aarch64-unknown-linux-gnu": "6b7cae3a8fc4385a59dea3146fcb8bad7fea4230e0ad36a8c692afacbc254be0",
    "x86_64-apple-darwin": "c1b8b89a81e91b2a8b3f96def3195d08cfe3a105651da7908d53061f7140510d",
    "x86_64-pc-windows-msvc": "171efab55ac6b9881fd53ee4c20f8bf3bb1340ffc618483746909014db12216a",
    "x86_64-unknown-linux-gnu": "8b010a3b1a4a0188a67cdb8a7a27348b2a501af78aec7fc74f2ace167368d530",
  },
};

/** The pinned sha256 for one version/target pair, or undefined when unknown. */
export function sidecarSha256(pin: string, target: DenoReleaseTarget): string | undefined {
  return DENO_SIDECAR_PINS[pin]?.[target];
}
