// Regenerate src/copilot_api/sidecar_pins.ts for the version in .dvmrc.
//
// The sidecar download refuses any archive it cannot verify, so every supported target
// needs a checked-in sha256. Deno publishes one per asset (`<asset>.sha256sum`), which
// is what this reads -- a few hundred bytes each, rather than hashing five ~40MB zips.
//
// The table is a TS module, not a data file, so it is part of the module graph: a
// compiled binary carries it with no separate embedding step.
//
// Run after bumping .dvmrc, then commit the result.
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { DENO_RELEASE_TARGETS, readDvmrcPin } from "../src/copilot_api/sidecar.ts";
import { PROJECT_ROOT } from "../src/utils/root.ts";

const pin = readDvmrcPin(PROJECT_ROOT);
const targets = [...new Set(Object.values(DENO_RELEASE_TARGETS))].sort();

const entries: string[] = [];
for (const target of targets) {
  const url =
    `https://github.com/denoland/deno/releases/download/v${pin}/deno-${target}.zip.sha256sum`;
  const response = await fetch(url);
  if (!response.ok) throw new Error(`HTTP ${response.status} for ${url}`);
  // Two formats ship side by side: the POSIX `sha256sum` line (`<hex>  <file>`) and,
  // for the Windows targets, PowerShell Get-FileHash output (`Hash : <HEX>`). Pull the
  // first 64-hex-digit token out of either and normalise the case.
  const text = await response.text();
  const digest = (/\b[0-9a-fA-F]{64}\b/.exec(text)?.[0] ?? "").toLowerCase();
  if (digest === "") {
    throw new Error(`${url} did not yield a sha256 (got '${text.trim().slice(0, 40)}')`);
  }
  entries.push(`    "${target}": "${digest}",`);
  console.error(`  ${target} ${digest}`);
}

const source = `// GENERATED by scripts/pin-deno-sidecar.ts -- run it after bumping .dvmrc.
//
// sha256 of each pinned deno release archive. downloadSidecar REFUSES a target with no
// entry here rather than installing an unverifiable binary, so this table is the thing
// that makes sidecar provisioning safe.
import type { DenoReleaseTarget } from "./sidecar.ts";

export const DENO_SIDECAR_PINS: Readonly<
  Record<string, Readonly<Partial<Record<DenoReleaseTarget, string>>>>
> = {
  "${pin}": {
${entries.join("\n")}
  },
};

/** The pinned sha256 for one version/target pair, or undefined when unknown. */
export function sidecarSha256(pin: string, target: DenoReleaseTarget): string | undefined {
  return DENO_SIDECAR_PINS[pin]?.[target];
}
`;

const out = join(PROJECT_ROOT, "src", "copilot_api", "sidecar_pins.ts");
writeFileSync(out, source);
console.log(`wrote ${out} for deno v${pin}`);
